version: '3'
services:
  master:
    build:
      context: .
      dockerfile: ./controller.Dockerfile
    working_dir: /root/playbooks
    volumes:
      - /home/abdellah/Bureau/ansible/playbooks:/root/playbooks
      - /home/abdellah/Bureau/ansible/config:/etc/ansible
    command: tail -f /dev/null

  web:
    build:
      context: .
      dockerfile: ./webserver.Dockerfile

  db:
    build:
      context: .
      dockerfile: ./webserver.Dockerfile

  lb:
    build:
      context: .
      dockerfile: ./webserver.Dockerfile
    ports:
    - 8080:80
